### ISSUE TITLE
Sign up and sign in pages 

### ISSUE THREAD

**Issue by Eazyisreal** [zuri-training/Proj-T_C_GEN__Team-77#17]
Write codes for already designed sign up and sign in pages

**Comment by Rhoda-Codes** [comment]
https://github.com/Rhoda-Codes/Team_77-S-I

**Comment by Rhoda-Codes** [comment]
https://github.com/Rhoda-Codes/Sign-up-page

**Comment by Rhoda-Codes** [comment]
https://github.com/Rhoda-Codes/Sign-up-pop-up
