### ISSUE TITLE
Design the Contact us page

### ISSUE THREAD

**Issue by AbimbolaAdegoke** [zuri-training/Proj-T_C_GEN__Team-77#27]
The users must be able to input their feedbacks or send their challenges across to us.

**Comment by Chris246824** [comment]
oh okay

**Comment by Ashraf911** [comment]
I designed the contact us page.
https://www.figma.com/file/6yoI3SiBYMV9IKHClcKfaR/Terms77?node-id=1364%3A15364

**Comment by Eazyisreal** [comment]
Amazing work done
